# Pytest configuration file
[pytest]

#=================================================== Run flags =========================================================
# Автоматическое добавление флагов при запуске тестов (pytest ↲)
# -s - выключает отображение в консоли (вывод)
# -v - увеличивает уровень логирования (verbose)
# -k - фильтр по названию (ключевому слову) (например: -k "login")
# -m - фильтр по маркеру (например: -m "smoke")

addopts = -s -v

# C сохранением Allure отчета (с отчисткой перед запуском)
#addopts = -s -v --alluredir=./allure-results --clean-alluredir

#=================================================== Find test =========================================================
# Файлы с тестами (default - <test_*.py *_test.py>)
python_files = test_*.py

# Классы с тестами (default)
python_classes = Test*

# Функции (методы) с тестами (default)
python_functions = test_*


#=================================================== Markers ===========================================================
# Кастомные маркеры (⚠️что бы не вылазило <PytestUnknownMarkWarning ========= warnings summary ========>)
markers =
    smoke:       Smoke тесты
    regression:  Регрессионные тесты
    negative:    Негативные тесты
    -----------
    registration: Тесты, связанные с регистрацией нового пользователя
    auth:         Тесты, связанные с авторизацией (Log in)
    dashboard:    Тесты, связанные с Dashboard page
    courses:      Тесты, связанные с курсами
    exercises:    Тесты, связанные с заданиями
    files:        Тесты, связанные с файлами (Load/Upload)



#                                                     ⬇︎ ИЛИ ⬇︎
#============================================ Warnings ignore (BAD PRACTICE)============================================
# Игнорирование предупреждений (PytestWarning)
filterwarnings =
#    ignore::pytest.PytestUnknownMarkWarning


#=================================================== Logging ===========================================================
# Формат записей, которые pytest перехватывает из logging (именно их Allure прикрепляет к отчету - секция log)
log_format =  %(levelname)s | %(name)s: %(message)s

#=======================================================================================================================
